### ISSUE TITLE
eMMC Lenta

### ISSUE THREAD

**Issue by Jatsotserah** [Vampitech/NeXT#1]
Vampi, como no hay forma de contactarlo, le escribo por acá. Vi que tenía problemas con la eMMC que se congela por segundos indistintamente del tamaño de ajuste que se le haga. A mí también me sucedía lo mismo pero me puse a probar y logré curarlo con el mismo setup.
Pienso que el problema está al momento de formatear la mSD. El DiskGenius marca bien la primera partición pero al darle a la segunda, la tiene por defecto en NTFS pero cuando se cambia a FAT32, no se cambia el cluster. Le cambié el cluster a 64k y **no la oculté al instante**.

Cabe señalar que es una mSD A1. También agrego que cuando estaba lenta la eMMC la había formateado dentro del DiskGenius.
Pero en el último intento, le di primero _clean_ en diskpart para curar y de ahí, formato a exFAT en Windows como normalmente se hace. Luego seguí con el DiskGenius como normalmente se hace el proceso. Ya después de todo instalado, volví a ocultarla y todo bien.

Al menos esos asuntos hicieron que saliera con normal fluidez la eMMC.

Saludos desde Panamá.

PS: Días después se puso lenta de nuevo. Volví a formatear la partición de eMMC con FAT32 Format a 32k de cluster y de momento todo bien.

**Comment by Jatsotserah** [comment]
El asunto vuelve a fallar cuando se usan ciertos juegos como Pokemon. No queda otra que usan la eMMC full 32gb

**Comment by Vampitech** [comment]
Correcto, la emuMMC completa es la mejor opción.
