### ISSUE TITLE
Hekate Sin GUI

### ISSUE THREAD

**Issue by Eduflasher** [Vampitech/NeXT#4]
Buenas tardes Vampi:

Encontre tu canal gracias a un compañero que tambien modea y probe Next sin problemas para el flasheo. Pero al realizarlo en otra Switch me di cuenta que no le funciona el Digitalizador por un problema en la placa (se cambio el digitalizador, modulo de cartuchos y display) . Por lo cual te consulto si habra alguna manera de que en el pack de Next incluyas el Hekate sin el GUI o si hay alguna manera para poder obiar el Touchscreen y hacerlo con botones fisicos o con algun accesorio. 

Muchas gracias, se valora todo el esfuerzo en esta gran compilacion. Ojala tengas un momento para leer este mj.
Saludos desde Argentina.

PD: Sub y Like siempre en YT !

**Comment by Vampitech** [comment]
Saludos amigo, 

Primero que nada, gracias por tu apoyo y la confianza. Hay una forma de ejecutar Hekate sin GUI y es renombrando o eliminando el archivo NYX.BIN que se encuentra dentro de la carpeta BOOTLOADER/SYS. Sin embargo, esto hará que Hekate corra con funciones limitadas entre las cuales no podrás hacer crear/asignar/iniciar emunand Pero, si podrás ejecutar Atmosphere o incluso ir a OFW. 

Espero te sirva este dato.

**Comment by Eduflasher** [comment]
Gracias por tu pronta y excelente respuesta, que bueno que tengas ese espiritu de compartir conocimiento. Ojala YT entendiera eso y dejara volver a tener toda tu biblioteca de Vídeos sin meter censura o darlos de baja. Pero bueno por suerte Github esta firme. Buena suerte en todos los proyectos que arranques y ojala Next siga creciendo...Ya me pongo a hacer pruebas con esa switch sin touchscreen...
Gracias nuevamente compa...

**Comment by Vampitech** [comment]
Con el mayor gusto, amigo. Esperemos que algún día haya una plataforma libre de yugos comerciales que permiten que las empresas ejerzan dictaduras y censuras. Por ahora aquí estaré firme.

Saludos!
