### ISSUE TITLE
next.uf2

### ISSUE THREAD

**Issue by oresterosso75** [Vampitech/NeXT#5]
is it possible to have uf2 files for internal mod-chip?

**Comment by Vampitech** [comment]
what kind of modchip you have on your console?

**Comment by oresterosso75** [comment]
RcmX86 by euclala

**Comment by Vampitech** [comment]
NeXT is based on a PAYLOAD.BIN file stored on the SD root. You need an uf2 that can load that file. I searched in their official Github repo and i found this https://github.com/euclala/sd_bin_reload_RCM-X86.

I don't have a modchip on my switch to test but maybe this will work on yours. So let me know

**Comment by oresterosso75** [comment]
I'll try it and let you know.
thanks
